[versions]
kotlin = "2.1.21"
buildLogic = "1.0.0"
ktlint = "12.3.0"

# Build logic plugin release information
buildLogicPlugin-groupId = "com.build.logic.plugin"
buildLogicPlugin-version = "1.0.0"
buildLogicPlugin-implementationClass = "com.build.logic.BuildLogic"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
build-logic = { id = "com.build.logic.plugin" }
java-gradle = { id = "java-gradle-plugin" }
kotlin-compiler = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }