[versions]
kotlin = "2.1.21"
buildLogic = "1.0.0"
ktlint = "12.3.0"

# Build logic plugin release information
buildLogicPlugin-groupId = "com.build.logic.plugin"
buildLogicPlugin-version = "1.0.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-compiler = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
build-logic = { id = "com.build.logic.plugin", version.ref = "buildLogic" }
java-gradle = { id = "java-gradle-plugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }