[versions]
kotlin = "2.1.21"
ktlint = "12.3.0"

# Build logic plugin release information
buildLogicPlugin-groupId = "com.build.logic.plugin"
buildLogicPlugin-version = "1.0.0"

[libraries]

[plugins]
kotlin-compiler = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
java-gradle = { id = "java-gradle-plugin" }